In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# need to remove all the """ strings

# Do not use upyter Notebook

# takes too long

# load relevant libraries
import numpy as np
import pandas as pd
import pickle

# Helper function to split our data
from sklearn.model_selection import train_test_split

# Helper fuctions to evaluate our model.
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score, roc_auc_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

# Import our Random Forest
from sklearn.ensemble import RandomForestClassifier

# Library for visualizing our tree
# If you get an error, run 'conda install python-graphviz' in your terminal (without the quotes).


In [3]:
df = pd.read_csv('/content/drive/MyDrive/SQLproject/data/final_model_data.csv')
# encode = {'E' : 0,
#           'E10+': 1,
#           'T' : 2,
#           'M' : 3,
#           'AO':4}
# df["esrb_encoded"] = df["esrb_rating"].map(encode)

# df = df['game_title',
#         'esrb_rating',
#         'content_descriptors',
#        'interactive_elements',
#         'content_summary',
#         'platform',
#         'release_date',
#        'updated',
#         'developers',
#         'genres',
#         'publisher',
#        'na_sales',
#         'eu_sales',
#         'jp_sales',
#         'other_sales',
#         'global_sales',
#         'Alcohol Reference',
#         'Alcohol and Tobacco Reference',
#         'Animated Blood',
#         'Animated Blood and Gore',
#         'Animated Violence',
#         'Blood',
#         'Blood and Gore',
#         'Cartoon Violence',
#         'Comic Mischief',
#         'Crude Humor',
#         'Drug Reference',
#         'Drug and Alcohol Reference',
#         'Edutainment',
#         'Fantasy Violence',
#         'Gambling',
#         'Gambling Themes',
#         'Gaming',
#         'Informational',
#         'Intense Violence',
#         'Language',
#         'Lyrics',
#         'Mature Humor',
#         'Mature Sexual Themes',
#         'Mild Animated Blood',
#         'Mild Animated Violence',
#         'Mild Blood',
#         'Mild Cartoon Violence',
#         'Mild Fantasy Violence',
#         'Mild Language',
#         'Mild Lyrics',
#         'Mild Realistic Violence',
#         'Mild Sexual Themes',
#         'Mild Suggestive Themes',
#         'Mild Violence',
#         'Nudity',
#         'Number of Descriptors',
#         'Partial Nudity',
#         'Realistic Blood',
#         'Realistic Blood and Gore',
#         'Realistic Violence',
#         'Sexual Content',
#         'Sexual Themes',
#         'Sexual Violence',
#         'Simulated Gambling',
#         'Strong Language',
#         'Strong Lyrics',
#         'Strong Sexual Content',
#         'Suggestive Themes',
#         'Suitable for All Users',
#         'Suitable for Mature Users',
#         'Tobacco Reference',
#         'Use of Alcohol',
#         'Use of Alcohol and Tobacco',
#         'Use of Drugs',
#         'Use of Drugs and Alcohol',
#         'Use of Tobacco',
#         'Violence',
#         'Violent References',
#         'release_year']

# df.to_csv('/content/drive/MyDrive/SQLproject/data/final_model_data.csv', index=False)

In [69]:
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', None)
resultIndices = []
user_descriptors = ['Cartoon Violence','Mild Language']
for c in user_descriptors:
  if len(resultIndices)>0:
    resultIndices = resultIndices.intersection(df[df[c]==1].index)
  else:
    resultIndices=df[df[c]==1].index

# df.loc[resultIndices, ['game_title', 'esrb_rating','content_descriptors']]
df.iloc[resultIndices].sort_values(by='release_year')

game_title esrb_rating  \
232                         Battletoads        E10+   
5631                        Battletoads        E10+   
5800   Wanted: A Wild Western Adventure           E   
45752                            Daxter        E10+   
24260         Bleach: The Blade of Fate           T   
...                                 ...         ...   
10932               Super Bomberman R 2        E10+   
11822               Super Bomberman R 2        E10+   
34949          Super Bomberman R Online        E10+   
19466               Super Bomberman R 2        E10+   
11867                 Streets of Rage 4           T   

                                     content_descriptors  \
232    Animated Blood,Cartoon Violence,Crude Humor,Mi...   
5631   Animated Blood,Cartoon Violence,Crude Humor,Mi...   
5800   Cartoon Violence,Mild Language,Use of Alcohol ...   
45752  Animated Blood,Cartoon Violence,Crude Humor,Mi...   
24260                     Cartoon Violence,Mild Language   
...                                                  ...   
10932          Cartoon Violence,Mild Blood,Mild Language   
11822          Cartoon Violence,Mild Blood,Mild Language   
34949          Cartoon Violence,Mild Blood,Mild Language   
19466          Cartoon Violence,Mild Blood,Mild Language   
11867  Cartoon Violence,Mild Language,Mild Suggestive...   

                             interactive_elements  \
232                       No Interactive Elements   
5631                      No Interactive Elements   
5800                      No Interactive Elements   
45752                     No Interactive Elements   
24260  Online Interactions Not Rated by the ESRB.   
...                                           ...   
10932                             Users Interact.   
11822                             Users Interact.   
34949          Users Interact, In-Game Purchases.   
19466                             Users Interact.   
11867                     No Interactive Elements   

                                         content_summary       platform  \
232    This is an action game in which players assume...       Xbox One   
5631   This is an action game in which players assume...     Windows PC   
5800                                   No Rating Summary     Windows PC   
45752                                  No Rating Summary            PSP   
24260                                  No Rating Summary    Nintendo DS   
...                                                  ...            ...   
10932  This is an action-adventure game in which play...       Xbox One   
11822  This is an action-adventure game in which play...  PlayStation 4   
34949  This is an online action game in which players...         Stadia   
19466  This is an action-adventure game in which play...     Windows PC   
11867  This is an action-fighting game in which playe...         Stadia   

      release_date              updated  \
232     1991-06-01  2020-08-27T22:09:11   
5631    1991-06-01  2020-08-27T22:09:11   
5800    2004-06-24  2019-01-09T12:41:06   
45752   2006-03-14  2020-02-02T02:49:16   
24260   2006-01-26  2020-01-15T11:21:30   
...            ...                  ...   
10932          NaN                  NaN   
11822          NaN                  NaN   
34949          NaN                  NaN   
19466          NaN                  NaN   
11867          NaN                  NaN   

                                             developers  \
232    Rare, Arc System Works, Mindscape, Dlala Studios   
5631   Rare, Arc System Works, Mindscape, Dlala Studios   
5800                                        Revistronic   
45752                        Naughty Dog, Ready At Dawn   
24260                                          Treasure   
...                                                 ...   
10932                                               NaN   
11822                                               NaN   
34949                                               NaN   
19

In [101]:
exactIndices = [1, 1068, 11867]
exactIndices = df.iloc[exactIndices].index
exactIndices.intersection(df[df['release_year']==2022].index)

Index([11867], dtype='int64')

In [91]:
user_descriptors = ['Mild Language', 'Cartoon Violence']

stringDscrp = ",".join(sorted(user_descriptors))
for i in range(len(df)):
  if df.loc[i, 'content_descriptors'] == stringDscrp:
    print(df.iloc[i])


NameError: name 'st' is not defined

In [35]:
selected_features = list(df.columns) #36
selected_features = [ele for ele in selected_features if ele not in ['game_title', 'esrb_rating', 'content_descriptors',
       'interactive_elements', 'content_summary', 'platform', 'release_date',
       'updated', 'developers', 'genres', 'publisher',
       'na_sales', 'eu_sales', 'jp_sales', 'other_sales', 'global_sales',  'esrb_encoded']]

In [36]:
X = df[selected_features]

y = df["esrb_encoded"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

In [37]:
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)
y_pred = rfc.predict(X_test)
print(classification_report(y_pred, y_test))
print(confusion_matrix(y_true=y_test, y_pred=y_pred))
rfc.get_params()

              precision    recall  f1-score   support

           0       0.93      0.92      0.93      3940
           1       0.78      0.78      0.78      1366
           2       0.85      0.84      0.84      2614
           3       0.91      0.94      0.92      1257
           4       0.17      0.50      0.25         2

    accuracy                           0.88      9179
   macro avg       0.73      0.80      0.74      9179
weighted avg       0.88      0.88      0.88      9179

[[3643  131  151    1    1]
 [ 139 1070  155    0    0]
 [ 152  164 2191   76    0]
 [   6    1  116 1176    0]
 [   0    0    1    4    1]]


{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [ ]:
# Streamlit App
# matching so dont need to worry about conflictions

# needed to save it myself


pickle.dump(rfc, open('/content/drive/MyDrive/SQLproject/models/final_model2.pkl', 'wb'))


In [ ]:
X_train.columns

Index(['Alcohol Reference', 'Alcohol and Tobacco Reference', 'Animated Blood',
       'Animated Blood and Gore', 'Animated Violence', 'Blood',
       'Blood and Gore', 'Cartoon Violence', 'Comic Mischief', 'Crude Humor',
       'Drug Reference', 'Drug and Alcohol Reference', 'Edutainment',
       'Fantasy Violence', 'Gambling', 'Gambling Themes', 'Gaming',
       'Informational', 'Intense Violence', 'Language', 'Lyrics',
       'Mature Humor', 'Mature Sexual Themes', 'Mild Animated Blood',
       'Mild Animated Violence', 'Mild Blood', 'Mild Cartoon Violence',
       'Mild Fantasy Violence', 'Mild Language', 'Mild Lyrics',
       'Mild Realistic Violence', 'Mild Sexual Themes',
       'Mild Suggestive Themes', 'Mild Violence', 'Nudity',
       'Number of Descriptors', 'Partial Nudity', 'Realistic Blood',
       'Realistic Blood and Gore', 'Realistic Violence', 'Sexual Content',
       'Sexual Themes', 'Sexual Violence', 'Simulated Gambling',
       'Strong Language', 'Strong Lyrics', '