In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# need to remove all the """ strings

# Do not use upyter Notebook

# takes too long

# load relevant libraries
import numpy as np
import pandas as pd
import pickle

# Helper function to split our data
from sklearn.model_selection import train_test_split

# Helper fuctions to evaluate our model.
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score, roc_auc_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

# Import our Random Forest
from sklearn.ensemble import RandomForestClassifier

# Library for visualizing our tree
# If you get an error, run 'conda install python-graphviz' in your terminal (without the quotes).


In [3]:
df = pd.read_csv('/content/drive/MyDrive/SQLproject/CombinedESRBdata.csv')

In [4]:
encode = {'E' : 0,
          'E10+': 1,
          'T' : 2,
          'M' : 3,
          'AO':4}
df["esrb_encoded"] = df["esrb_rating"].map(encode)

In [6]:
selected_features = [ 'release_year',
       'na_sales', 'eu_sales', 'jp_sales', 'other_sales', 'global_sales',
       'Number of Descriptors', 'Crude Humor', 'Mild Cartoon Violence',
       'Cartoon Violence', 'Mild Language', 'Mild Violence', 'Violence',
       'Blood and Gore', 'Language', 'Nudity', 'Sexual Themes',
       'Mild Fantasy Violence', 'Alcohol Reference', 'Mild Suggestive Themes',
       'Simulated Gambling', 'Fantasy Violence', 'Mild Blood',
       'Use of Alcohol', 'Use of Tobacco', 'Drug Reference', 'Strong Language',
       'Suggestive Themes', 'Blood', 'Partial Nudity', 'Tobacco Reference',
       'Comic Mischief', 'Animated Blood', 'Intense Violence',
       'Alcohol and Tobacco Reference', 'Violent References',
       'Strong Sexual Content', 'Use of Alcohol and Tobacco', 'Use of Drugs',
       'Mild Lyrics', 'Lyrics', 'Use of Drugs and Alcohol',
       'Animated Violence', 'Mild Sexual Themes', 'Sexual Content',
       'Drug and Alcohol Reference', 'Strong Lyrics', 'Mature Humor',
       'Edutainment', 'Gambling', 'Animated Blood and Gore', 'Informational',
       'Mature Sexual Themes', 'Mild Animated Violence', 'Gaming',
       'Realistic Violence', 'Realistic Blood', 'Suitable for Mature Users',
       'Gambling Themes', 'Realistic Blood and Gore', 'Sexual Violence',
       'Mild Realistic Violence', 'Suitable for All Users',
       'Mild Animated Blood']

In [7]:
dfs = df[selected_features].copy()
dfs = dfs.drop(columns=['na_sales','eu_sales','jp_sales','other_sales','global_sales'])

In [8]:
X = dfs

y = df["esrb_encoded"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

In [9]:
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)
y_pred = rfc.predict(X_test)
print(classification_report(y_pred, y_test))
print(confusion_matrix(y_true=y_test, y_pred=y_pred))
rfc.get_params()

              precision    recall  f1-score   support

           0       0.93      0.93      0.93      3940
           1       0.79      0.79      0.79      1364
           2       0.85      0.84      0.84      2625
           3       0.90      0.94      0.92      1248
           4       0.17      0.50      0.25         2

    accuracy                           0.88      9179
   macro avg       0.73      0.80      0.75      9179
weighted avg       0.88      0.88      0.88      9179

[[3646  136  143    1    1]
 [ 134 1072  158    0    0]
 [ 155  155 2200   73    0]
 [   5    1  123 1170    0]
 [   0    0    1    4    1]]


{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [10]:
# Streamlit App
# matching so dont need to worry about conflictions

# needed to save it myself


pickle.dump(rfc, open('/content/drive/MyDrive/SQLproject/final_model.pkl', 'wb'))
