In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# need to remove all the """ strings

# Do not use upyter Notebook

# takes too long

# load relevant libraries
import numpy as np
import pandas as pd
import pickle

# Helper function to split our data
from sklearn.model_selection import train_test_split

# Helper fuctions to evaluate our model.
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score, roc_auc_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

# Import our Random Forest
from sklearn.ensemble import RandomForestClassifier

# Library for visualizing our tree
# If you get an error, run 'conda install python-graphviz' in your terminal (without the quotes).


In [28]:
df = pd.read_csv('/content/drive/MyDrive/SQLproject/data/final_model_data.csv')
# encode = {'E' : 0,
#           'E10+': 1,
#           'T' : 2,
#           'M' : 3,
#           'AO':4}
# df["esrb_encoded"] = df["esrb_rating"].map(encode)

# df = df['game_title',
#         'esrb_rating',
#         'content_descriptors',
#        'interactive_elements',
#         'content_summary',
#         'platform',
#         'release_date',
#        'updated',
#         'developers',
#         'genres',
#         'publisher',
#        'na_sales',
#         'eu_sales',
#         'jp_sales',
#         'other_sales',
#         'global_sales',
#         'Alcohol Reference',
#         'Alcohol and Tobacco Reference',
#         'Animated Blood',
#         'Animated Blood and Gore',
#         'Animated Violence',
#         'Blood',
#         'Blood and Gore',
#         'Cartoon Violence',
#         'Comic Mischief',
#         'Crude Humor',
#         'Drug Reference',
#         'Drug and Alcohol Reference',
#         'Edutainment',
#         'Fantasy Violence',
#         'Gambling',
#         'Gambling Themes',
#         'Gaming',
#         'Informational',
#         'Intense Violence',
#         'Language',
#         'Lyrics',
#         'Mature Humor',
#         'Mature Sexual Themes',
#         'Mild Animated Blood',
#         'Mild Animated Violence',
#         'Mild Blood',
#         'Mild Cartoon Violence',
#         'Mild Fantasy Violence',
#         'Mild Language',
#         'Mild Lyrics',
#         'Mild Realistic Violence',
#         'Mild Sexual Themes',
#         'Mild Suggestive Themes',
#         'Mild Violence',
#         'Nudity',
#         'Number of Descriptors',
#         'Partial Nudity',
#         'Realistic Blood',
#         'Realistic Blood and Gore',
#         'Realistic Violence',
#         'Sexual Content',
#         'Sexual Themes',
#         'Sexual Violence',
#         'Simulated Gambling',
#         'Strong Language',
#         'Strong Lyrics',
#         'Strong Sexual Content',
#         'Suggestive Themes',
#         'Suitable for All Users',
#         'Suitable for Mature Users',
#         'Tobacco Reference',
#         'Use of Alcohol',
#         'Use of Alcohol and Tobacco',
#         'Use of Drugs',
#         'Use of Drugs and Alcohol',
#         'Use of Tobacco',
#         'Violence',
#         'Violent References',
#         'release_year']

# df.to_csv('/content/drive/MyDrive/SQLproject/data/final_model_data.csv', index=False)

In [29]:
df.columns

Index(['game_title', 'esrb_rating', 'content_descriptors',
       'interactive_elements', 'content_summary', 'platform', 'release_date',
       'updated', 'developers', 'genres', 'publisher', 'na_sales', 'eu_sales',
       'jp_sales', 'other_sales', 'global_sales', 'Alcohol Reference',
       'Alcohol and Tobacco Reference', 'Animated Blood',
       'Animated Blood and Gore', 'Animated Violence', 'Blood',
       'Blood and Gore', 'Cartoon Violence', 'Comic Mischief', 'Crude Humor',
       'Drug Reference', 'Drug and Alcohol Reference', 'Edutainment',
       'Fantasy Violence', 'Gambling', 'Gambling Themes', 'Gaming',
       'Informational', 'Intense Violence', 'Language', 'Lyrics',
       'Mature Humor', 'Mature Sexual Themes', 'Mild Animated Blood',
       'Mild Animated Violence', 'Mild Blood', 'Mild Cartoon Violence',
       'Mild Fantasy Violence', 'Mild Language', 'Mild Lyrics',
       'Mild Realistic Violence', 'Mild Sexual Themes',
       'Mild Suggestive Themes', 'Mild Violence

In [30]:
selected_features = list(df.columns) #36
selected_features = [ele for ele in selected_features if ele not in ['game_title', 'esrb_rating', 'content_descriptors',
       'interactive_elements', 'content_summary', 'platform', 'release_date',
       'updated', 'developers', 'genres', 'publisher',
       'na_sales', 'eu_sales', 'jp_sales', 'other_sales', 'global_sales',  'esrb_encoded']]

In [31]:
X = df[selected_features]

y = df["esrb_encoded"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

In [32]:
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)
y_pred = rfc.predict(X_test)
print(classification_report(y_pred, y_test))
print(confusion_matrix(y_true=y_test, y_pred=y_pred))
rfc.get_params()

              precision    recall  f1-score   support

           0       0.93      0.92      0.93      3954
           1       0.78      0.78      0.78      1361
           2       0.85      0.84      0.84      2616
           3       0.90      0.94      0.92      1246
           4       0.17      0.50      0.25         2

    accuracy                           0.88      9179
   macro avg       0.72      0.80      0.74      9179
weighted avg       0.88      0.88      0.88      9179

[[3649  135  141    1    1]
 [ 141 1063  160    0    0]
 [ 159  162 2189   73    0]
 [   5    1  125 1168    0]
 [   0    0    1    4    1]]


{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [35]:
# Streamlit App
# matching so dont need to worry about conflictions

# needed to save it myself


pickle.dump(rfc, open('/content/drive/MyDrive/SQLproject/models/final_model2.pkl', 'wb'))


In [33]:
X_train.columns

Index(['Alcohol Reference', 'Alcohol and Tobacco Reference', 'Animated Blood',
       'Animated Blood and Gore', 'Animated Violence', 'Blood',
       'Blood and Gore', 'Cartoon Violence', 'Comic Mischief', 'Crude Humor',
       'Drug Reference', 'Drug and Alcohol Reference', 'Edutainment',
       'Fantasy Violence', 'Gambling', 'Gambling Themes', 'Gaming',
       'Informational', 'Intense Violence', 'Language', 'Lyrics',
       'Mature Humor', 'Mature Sexual Themes', 'Mild Animated Blood',
       'Mild Animated Violence', 'Mild Blood', 'Mild Cartoon Violence',
       'Mild Fantasy Violence', 'Mild Language', 'Mild Lyrics',
       'Mild Realistic Violence', 'Mild Sexual Themes',
       'Mild Suggestive Themes', 'Mild Violence', 'Nudity',
       'Number of Descriptors', 'Partial Nudity', 'Realistic Blood',
       'Realistic Blood and Gore', 'Realistic Violence', 'Sexual Content',
       'Sexual Themes', 'Sexual Violence', 'Simulated Gambling',
       'Strong Language', 'Strong Lyrics', '